import { useEffect, useState } from 'react';

export type AppLanguage = 'en' | 'my' | 'ko';

export const languageOptions: Array<{ value: AppLanguage; label: string; shortLabel: string }> = [
  { value: 'en', label: 'English', shortLabel: 'EN' },
  { value: 'my', label: 'Myanmar', shortLabel: 'MY' },
  { value: 'ko', label: 'Korean', shortLabel: 'KO' },
];

const storageKey = 'ki3-language';

function isAppLanguage(value: string | null): value is AppLanguage {
  return value === 'en' || value === 'my' || value === 'ko';
}

export function currentLanguage(): AppLanguage {
  if (typeof window === 'undefined') return 'en';
  const saved = window.localStorage.getItem(storageKey);
  return isAppLanguage(saved) ? saved : 'en';
}

export function saveLanguage(language: AppLanguage) {
  window.localStorage.setItem(storageKey, language);
  document.documentElement.lang = language;
  window.dispatchEvent(new CustomEvent('ki3-language-change', { detail: language }));
}

export function useLanguage() {
  const [language, setLanguage] = useState<AppLanguage>(() => currentLanguage());

  useEffect(() => {
    document.documentElement.lang = language;
    const update = () => setLanguage(currentLanguage());
    window.addEventListener('storage', update);
    window.addEventListener('ki3-language-change', update);
    return () => {
      window.removeEventListener('storage', update);
      window.removeEventListener('ki3-language-change', update);
    };
  }, [language]);

  return { language, setLanguage: saveLanguage, options: languageOptions };
}

export const dictionary: Record<string, Record<AppLanguage, string>> = {
  Dashboard: { en: 'Dashboard', my: 'Dashboard', ko: '대시보드' },
  'Shops (Tenants)': { en: 'Shops (Tenants)', my: 'ဆိုင်များ', ko: '매장 관리' },
  'Global Reports': { en: 'Global Reports', my: 'အစီရင်ခံစာများ', ko: '전체 보고서' },
  'System Settings': { en: 'System Settings', my: 'System Settings', ko: '시스템 설정' },
  'Order Monitor': { en: 'Order Monitor', my: 'Order Monitor', ko: '주문 모니터' },
  Inventory: { en: 'Inventory', my: 'ပစ္စည်းစာရင်း', ko: '재고' },
  Employees: { en: 'Employees', my: 'ဝန်ထမ်းများ', ko: '직원' },
  'Business Operations': { en: 'Business Operations', my: 'လုပ်ငန်းဆောင်ရွက်မှု', ko: '운영 관리' },
  'Branches & Finance': { en: 'Branches & Finance', my: 'ဆိုင်ခွဲနှင့်ငွေစာရင်း', ko: '지점 및 재무' },
  'Core Modules': { en: 'Core Modules', my: 'Core Modules', ko: '핵심 모듈' },
  Settings: { en: 'Settings', my: 'Settings', ko: '설정' },
  'Point of Sale': { en: 'Point of Sale', my: 'အရောင်း POS', ko: 'POS 판매' },
  'My Orders': { en: 'My Orders', my: 'ကျွန်ုပ်၏ Order များ', ko: '내 주문' },
  'Record Expense': { en: 'Record Expense', my: 'အသုံးစရိတ်ထည့်ရန်', ko: '비용 입력' },
  Reports: { en: 'Reports', my: 'Reports', ko: '보고서' },
  Subscription: { en: 'Subscription', my: 'Subscription', ko: '구독' },
  'Sign Out': { en: 'Sign Out', my: 'ထွက်ရန်', ko: '로그아웃' },
  'Global Search...': { en: 'Global Search...', my: 'ရှာရန်...', ko: '전체 검색...' },
  Notifications: { en: 'Notifications', my: 'အသိပေးချက်များ', ko: '알림' },
  'KI3 POS Administration': { en: 'KI3 POS Administration', my: 'KI3 POS စီမံခန့်ခွဲမှု', ko: 'KI3 POS 관리자' },
  'My Shop': { en: 'My Shop', my: 'ကျွန်ုပ်၏ဆိုင်', ko: '내 매장' },
  'Loading plan': { en: 'Loading plan', my: 'Plan ဖတ်နေသည်', ko: '요금제 로딩 중' },
  'Loading subscription...': { en: 'Loading subscription...', my: 'Subscription ဖတ်နေသည်...', ko: '구독 정보 로딩 중...' },
  'All stock levels look good': { en: 'All stock levels look good', my: 'Stock အခြေအနေကောင်းပါသည်', ko: '재고 상태가 양호합니다' },
  'Review tenant plans and shop activity.': { en: 'Review tenant plans and shop activity.', my: 'ဆိုင် plan နှင့် activity များစစ်ပါ။', ko: '매장 요금제와 활동을 확인하세요.' },
  'Return to the point of sale.': { en: 'Return to the point of sale.', my: 'POS သို့ပြန်သွားပါ။', ko: 'POS 화면으로 돌아갑니다.' },
  'Open inventory to review stock levels.': { en: 'Open inventory to review stock levels.', my: 'Stock စစ်ရန် Inventory ကိုဖွင့်ပါ။', ko: '재고 화면에서 수량을 확인하세요.' },
  Back: { en: 'Back', my: 'နောက်သို့', ko: '뒤로' },
  Online: { en: 'Online', my: 'Online', ko: '온라인' },
  'Offline queue': { en: 'Offline queue', my: 'Offline queue', ko: '오프라인 대기열' },
  Orders: { en: 'Orders', my: 'Order များ', ko: '주문' },
  Expense: { en: 'Expense', my: 'အသုံးစရိတ်', ko: '비용' },
  Held: { en: 'Held', my: 'Hold ထားသည်', ko: '보류' },
  'Close Shift': { en: 'Close Shift', my: 'Shift ပိတ်ရန်', ko: '근무 종료' },
  'Open Shift': { en: 'Open Shift', my: 'Shift ဖွင့်ရန်', ko: '근무 시작' },
  Language: { en: 'Language', my: 'ဘာသာစကား', ko: '언어' },
  'Change language': { en: 'Change language', my: 'ဘာသာစကားပြောင်းရန်', ko: '언어 변경' },
  'Loading KI3 POS…': { en: 'Loading KI3 POS…', my: 'KI3 POS ဖတ်နေသည်…', ko: 'KI3 POS 로딩 중…' },
  'KI3 POS could not load this page': { en: 'KI3 POS could not load this page', my: 'KI3 POS စာမျက်နှာ ဖွင့်မရပါ', ko: 'KI3 POS 페이지를 불러올 수 없습니다' },
  'Check your connection, then reload the application.': { en: 'Check your connection, then reload the application.', my: 'Connection စစ်ပြီး app ကိုပြန်ဖွင့်ပါ။', ko: '연결을 확인한 후 앱을 다시 로드하세요.' },
  'Reload application': { en: 'Reload application', my: 'App ပြန်ဖွင့်ရန်', ko: '앱 다시 로드' },
  'Access unavailable': { en: 'Access unavailable', my: 'ဝင်ခွင့်မရပါ', ko: '접근할 수 없습니다' },
  'Tenant Shops': { en: 'Tenant Shops', my: 'ဆိုင်များ', ko: '입점 매장' },
  'Subscriptions, access and tenant lifecycle management.': { en: 'Subscriptions, access and tenant lifecycle management.', my: 'Subscription, access နှင့် ဆိုင် lifecycle စီမံရန်။', ko: '구독, 접근 권한 및 매장 상태를 관리합니다.' },
  'Create New Shop': { en: 'Create New Shop', my: 'ဆိုင်အသစ်ဖန်တီးရန်', ko: '새 매장 만들기' },
  'Search shop, owner, email or ID…': { en: 'Search shop, owner, email or ID…', my: 'ဆိုင်၊ ပိုင်ရှင်၊ Email သို့ ID ရှာရန်…', ko: '매장, 소유자, 이메일 또는 ID 검색…' },
  'All statuses': { en: 'All statuses', my: 'Status အားလုံး', ko: '모든 상태' },
  Reactivate: { en: 'Reactivate', my: 'ပြန်ဖွင့်ရန်', ko: '재활성화' },
  'Stop / Suspend': { en: 'Stop / Suspend', my: 'ရပ်ဆိုင်းရန်', ko: '중지 / 정지' },
  'Archive shop': { en: 'Archive shop', my: 'ဆိုင် Archive လုပ်ရန်', ko: '매장 보관' },
  'Delete permanently': { en: 'Delete permanently', my: 'အပြီးဖျက်ရန်', ko: '영구 삭제' },
  'Register New Shop': { en: 'Register New Shop', my: 'ဆိုင်အသစ်မှတ်ပုံတင်ရန်', ko: '새 매장 등록' },
  'Unique Shop ID': { en: 'Unique Shop ID', my: 'ဆိုင် ID', ko: '고유 매장 ID' },
  'Shop Name': { en: 'Shop Name', my: 'ဆိုင်အမည်', ko: '매장 이름' },
  'Business Type': { en: 'Business Type', my: 'လုပ်ငန်းအမျိုးအစား', ko: '업종' },
  'Owner Name': { en: 'Owner Name', my: 'ပိုင်ရှင်အမည်', ko: '소유자 이름' },
  'Owner Email': { en: 'Owner Email', my: 'ပိုင်ရှင် Email', ko: '소유자 이메일' },
  'Temporary Password': { en: 'Temporary Password', my: 'ယာယီ Password', ko: '임시 비밀번호' },
  Phone: { en: 'Phone', my: 'ဖုန်း', ko: '전화번호' },
  Plan: { en: 'Plan', my: 'Plan', ko: '요금제' },
  'Initial State': { en: 'Initial State', my: 'စတင် Status', ko: '초기 상태' },
  'Subscription Start': { en: 'Subscription Start', my: 'Subscription စတင်ရက်', ko: '구독 시작일' },
  Cancel: { en: 'Cancel', my: 'မလုပ်တော့ပါ', ko: '취소' },
  'Create Shop': { en: 'Create Shop', my: 'ဆိုင်ဖန်တီးရန်', ko: '매장 만들기' },
  'Renew Subscription': { en: 'Renew Subscription', my: 'Subscription Renew လုပ်ရန်', ko: '구독 갱신' },
  'Renewal Start Date': { en: 'Renewal Start Date', my: 'Renewal စတင်ရက်', ko: '갱신 시작일' },
  'New Expiry': { en: 'New Expiry', my: 'Expiry အသစ်', ko: '새 만료일' },
  Amount: { en: 'Amount', my: 'ပမာဏ', ko: '금액' },
  'Record Payment & Renew': { en: 'Record Payment & Renew', my: 'Payment မှတ်ပြီး Renew လုပ်ရန်', ko: '결제 기록 및 갱신' },
  'Payment History': { en: 'Payment History', my: 'ငွေပေးချေမှုမှတ်တမ်း', ko: '결제 내역' },
  'Activity Logs': { en: 'Activity Logs', my: 'လုပ်ဆောင်ချက်မှတ်တမ်း', ko: '활동 로그' },
  'Global Settings': { en: 'Global Settings', my: 'Global Settings', ko: '전체 설정' },
  'Platform-wide branding, subscriptions, security and operations.': { en: 'Platform-wide branding, subscriptions, security and operations.', my: 'Branding, subscription, security နှင့် operations များ။', ko: '브랜딩, 구독, 보안 및 운영 설정입니다.' },
  'Save Changes': { en: 'Save Changes', my: 'ပြောင်းလဲမှုသိမ်းရန်', ko: '변경사항 저장' },
  Saving: { en: 'Saving…', my: 'သိမ်းနေသည်…', ko: '저장 중…' },
  Saved: { en: 'Saved', my: 'သိမ်းပြီး', ko: '저장됨' },
  'Branding & Locale': { en: 'Branding & Locale', my: 'Branding နှင့် Locale', ko: '브랜딩 및 지역 설정' },
  'System Name': { en: 'System Name', my: 'System အမည်', ko: '시스템 이름' },
  'Support Email': { en: 'Support Email', my: 'Support Email', ko: '지원 이메일' },
  'System Logo': { en: 'System Logo', my: 'System Logo', ko: '시스템 로고' },
  'Favicon URL': { en: 'Favicon URL', my: 'Favicon URL', ko: '파비콘 URL' },
  'Default Currency': { en: 'Default Currency', my: 'Default ငွေကြေး', ko: '기본 통화' },
  'Default Language': { en: 'Default Language', my: 'Default ဘာသာစကား', ko: '기본 언어' },
  'Default Timezone': { en: 'Default Timezone', my: 'Default Timezone', ko: '기본 시간대' },
  'Default Tax %': { en: 'Default Tax %', my: 'Default Tax %', ko: '기본 세금 %' },
  'Tax prices are inclusive': { en: 'Tax prices are inclusive', my: 'Tax ပါပြီးစျေးနှုန်း', ko: '세금 포함 가격' },
  'Products & Inventory': { en: 'Products & Inventory', my: 'Product နှင့် Inventory', ko: '상품 및 재고' },
  'Product catalog, traceable stock control and purchase receiving.': { en: 'Product catalog, traceable stock control and purchase receiving.', my: 'Product စာရင်း၊ stock history နှင့် purchase receiving စီမံရန်။', ko: '상품 목록, 재고 추적 및 입고를 관리합니다.' },
  Products: { en: 'Products', my: 'Product များ', ko: '상품' },
  'Stock Movement History': { en: 'Stock Movement History', my: 'Stock လှုပ်ရှားမှုမှတ်တမ်း', ko: '재고 이동 내역' },
  'Purchase Receiving': { en: 'Purchase Receiving', my: 'ဝယ်ယူပစ္စည်းလက်ခံခြင်း', ko: '구매 입고' },
  'All Products': { en: 'All Products', my: 'Product အားလုံး', ko: '전체 상품' },
  'In Stock': { en: 'In Stock', my: 'Stock ရှိ', ko: '재고 있음' },
  'Low Stock': { en: 'Low Stock', my: 'Stock နည်း', ko: '재고 부족' },
  'Out of Stock': { en: 'Out of Stock', my: 'Stock မရှိ', ko: '품절' },
  Inactive: { en: 'Inactive', my: 'မဖွင့်ထား', ko: '비활성' },
  'Search name, SKU, barcode or brand…': { en: 'Search name, SKU, barcode or brand…', my: 'အမည်၊ SKU၊ Barcode သို့ Brand ရှာရန်…', ko: '이름, SKU, 바코드 또는 브랜드 검색…' },
  'Add Product': { en: 'Add Product', my: 'Product ထည့်ရန်', ko: '상품 추가' },
  'Edit Product': { en: 'Edit Product', my: 'Product ပြင်ရန်', ko: '상품 수정' },
  'Product Name': { en: 'Product Name', my: 'Product အမည်', ko: '상품명' },
  'Item Type': { en: 'Item Type', my: 'Item အမျိုးအစား', ko: '항목 유형' },
  SKU: { en: 'SKU', my: 'SKU', ko: 'SKU' },
  Barcode: { en: 'Barcode', my: 'Barcode', ko: '바코드' },
  Category: { en: 'Category', my: 'Category', ko: '카테고리' },
  Brand: { en: 'Brand', my: 'Brand', ko: '브랜드' },
  Unit: { en: 'Unit', my: 'Unit', ko: '단위' },
  Supplier: { en: 'Supplier', my: 'Supplier', ko: '공급처' },
  'Cost Price': { en: 'Cost Price', my: 'အရင်းစျေး', ko: '원가' },
  'Selling Price': { en: 'Selling Price', my: 'ရောင်းစျေး', ko: '판매가' },
  'Discount %': { en: 'Discount %', my: 'Discount %', ko: '할인 %' },
  'Tax %': { en: 'Tax %', my: 'Tax %', ko: '세금 %' },
  'Online Price': { en: 'Online Price', my: 'Online စျေး', ko: '온라인 가격' },
  'In-store Price': { en: 'In-store Price', my: 'ဆိုင်တွင်းစျေး', ko: '매장 가격' },
  'Opening Stock': { en: 'Opening Stock', my: 'စတင် Stock', ko: '초기 재고' },
  'Minimum Stock': { en: 'Minimum Stock', my: 'အနည်းဆုံး Stock', ko: '최소 재고' },
  'Maximum Stock': { en: 'Maximum Stock', my: 'အများဆုံး Stock', ko: '최대 재고' },
  'Product Variants': { en: 'Product Variants', my: 'Product Variant များ', ko: '상품 옵션' },
  Description: { en: 'Description', my: 'ဖော်ပြချက်', ko: '설명' },
  Active: { en: 'Active', my: 'ဖွင့်ထား', ko: '활성' },
  'Track stock': { en: 'Track stock', my: 'Stock လိုက်မှတ်ရန်', ko: '재고 추적' },
  'Available online': { en: 'Available online', my: 'Online ရောင်းရန်', ko: '온라인 판매 가능' },
  'Available in-store': { en: 'Available in-store', my: 'ဆိုင်တွင်းရောင်းရန်', ko: '매장 판매 가능' },
  'Create Product': { en: 'Create Product', my: 'Product ဖန်တီးရန်', ko: '상품 생성' },
  'Update Product': { en: 'Update Product', my: 'Product ပြင်ဆင်ရန်', ko: '상품 업데이트' },
  'Owner Dashboard': { en: 'Owner Dashboard', my: 'ဆိုင်ရှင် Dashboard', ko: '소유자 대시보드' },
  'Live sales, profitability, stock and customer performance.': { en: 'Live sales, profitability, stock and customer performance.', my: 'အရောင်း၊ အမြတ်၊ stock နှင့် customer performance ကြည့်ရန်။', ko: '실시간 매출, 수익성, 재고 및 고객 성과를 확인합니다.' },
  'Export Daily Report': { en: 'Export Daily Report', my: 'နေ့စဉ် Report ထုတ်ရန်', ko: '일일 보고서 내보내기' },
  'Real-time Recent Orders': { en: 'Real-time Recent Orders', my: 'Real-time Recent Order များ', ko: '실시간 최근 주문' },
  'View All': { en: 'View All', my: 'အားလုံးကြည့်ရန်', ko: '전체 보기' },
  'No orders yet.': { en: 'No orders yet.', my: 'Order မရှိသေးပါ။', ko: '아직 주문이 없습니다.' },
  'No sales data yet.': { en: 'No sales data yet.', my: 'အရောင်း data မရှိသေးပါ။', ko: '아직 매출 데이터가 없습니다.' },
  'Branches & Daily Finance': { en: 'Branches & Daily Finance', my: 'ဆိုင်ခွဲနှင့်နေ့စဉ်ငွေစာရင်း', ko: '지점 및 일일 재무' },
  'Compare daily income, expenses and owner withdrawals by branch.': { en: 'Compare daily income, expenses and owner withdrawals by branch.', my: 'ဆိုင်ခွဲအလိုက် နေ့စဉ်ဝင်ငွေ၊ အသုံးစရိတ်၊ ပိုင်ရှင်ထုတ်ငွေ နှိုင်းယှဉ်ရန်။', ko: '지점별 일일 수입, 비용 및 소유자 인출을 비교합니다.' },
  'Report date': { en: 'Report date', my: 'Report ရက်စွဲ', ko: '보고서 날짜' },
  Branch: { en: 'Branch', my: 'ဆိုင်ခွဲ', ko: '지점' },
  Income: { en: 'Income', my: 'ဝင်ငွေ', ko: '수입' },
  'Operating Expenses': { en: 'Operating Expenses', my: 'လုပ်ငန်းအသုံးစရိတ်', ko: '운영 비용' },
  'Owner Withdrawals': { en: 'Owner Withdrawals', my: 'ပိုင်ရှင်ထုတ်ငွေ', ko: '소유자 인출' },
  Net: { en: 'Net', my: 'အသားတင်', ko: '순액' },
  'Add Shop Branch': { en: 'Add Shop Branch', my: 'ဆိုင်ခွဲထည့်ရန်', ko: '지점 추가' },
  'Branch name': { en: 'Branch name', my: 'ဆိုင်ခွဲအမည်', ko: '지점 이름' },
  Address: { en: 'Address', my: 'လိပ်စာ', ko: '주소' },
  'Add Branch': { en: 'Add Branch', my: 'ဆိုင်ခွဲထည့်ရန်', ko: '지점 추가' },
  'Employee Management': { en: 'Employee Management', my: 'ဝန်ထမ်းစီမံခန့်ခွဲမှု', ko: '직원 관리' },
  'Accounts, roles, granular permissions, performance and activity.': { en: 'Accounts, roles, granular permissions, performance and activity.', my: 'Account, role, permission, performance နှင့် activity များ။', ko: '계정, 역할, 권한, 성과 및 활동을 관리합니다.' },
  'Create Employee': { en: 'Create Employee', my: 'ဝန်ထမ်းထည့်ရန်', ko: '직원 생성' },
  'Search employee, email or phone…': { en: 'Search employee, email or phone…', my: 'ဝန်ထမ်း၊ Email သို့ ဖုန်း ရှာရန်…', ko: '직원, 이메일 또는 전화 검색…' },
  'All roles': { en: 'All roles', my: 'Role အားလုံး', ko: '모든 역할' },
  'Full Name': { en: 'Full Name', my: 'အမည်အပြည့်အစုံ', ko: '성명' },
  'Role Preset': { en: 'Role Preset', my: 'Role Preset', ko: '역할 프리셋' },
  Email: { en: 'Email', my: 'Email', ko: '이메일' },
  Shift: { en: 'Shift', my: 'Shift', ko: '근무' },
  'Assigned Branch': { en: 'Assigned Branch', my: 'သတ်မှတ်ထားသောဆိုင်ခွဲ', ko: '배정 지점' },
  'Action Permissions': { en: 'Action Permissions', my: 'လုပ်ဆောင်ခွင့်များ', ko: '작업 권한' },
  'Operational Access': { en: 'Operational Access', my: 'လုပ်ငန်းအသုံးပြုခွင့်', ko: '운영 접근' },
  'Business Profile': { en: 'Business Profile', my: 'လုပ်ငန်း Profile', ko: '비즈니스 프로필' },
  'Business type': { en: 'Business type', my: 'လုပ်ငန်းအမျိုးအစား', ko: '업종' },
  'Shop name': { en: 'Shop name', my: 'ဆိုင်အမည်', ko: '매장 이름' },
  'Receipt & Taxes': { en: 'Receipt & Taxes', my: 'Receipt နှင့် Tax', ko: '영수증 및 세금' },
  'Payment Accounts': { en: 'Payment Accounts', my: 'Payment Account များ', ko: '결제 계정' },
  'KPay, Wave & Bank Accounts': { en: 'KPay, Wave & Bank Accounts', my: 'KPay, Wave နှင့် Bank Account များ', ko: 'KPay, Wave 및 은행 계정' },
  'Display label (e.g. Main KPay)': { en: 'Display label (e.g. Main KPay)', my: 'ပြမည့်အမည် (ဥပမာ Main KPay)', ko: '표시 이름 (예: Main KPay)' },
  'Account holder name': { en: 'Account holder name', my: 'Account ပိုင်ရှင်အမည်', ko: '계정 소유자명' },
  'Account / phone number': { en: 'Account / phone number', my: 'Account / ဖုန်းနံပါတ်', ko: '계정 / 전화번호' },
  'Add Payment Account': { en: 'Add Payment Account', my: 'Payment Account ထည့်ရန်', ko: '결제 계정 추가' },
  'Search name, SKU or barcode': { en: 'Search name, SKU or barcode', my: 'အမည်၊ SKU သို့ Barcode ရှာရန်', ko: '이름, SKU 또는 바코드 검색' },
  'In-store': { en: 'In-store', my: 'ဆိုင်တွင်း', ko: '매장' },
  Cash: { en: 'Cash', my: 'ငွေသား', ko: '현금' },
  Card: { en: 'Card', my: 'Card', ko: '카드' },
  Credit: { en: 'Credit', my: 'အကြွေး', ko: '외상' },
  Split: { en: 'Split', my: 'ခွဲပေးချေ', ko: '분할' },
  'Complete Sale': { en: 'Complete Sale', my: 'အရောင်းပြီးဆုံးရန်', ko: '판매 완료' },
  'Open Shift to Sell': { en: 'Open Shift to Sell', my: 'ရောင်းရန် Shift ဖွင့်ပါ', ko: '판매하려면 근무를 시작하세요' },
  Daily: { en: 'Daily', my: 'နေ့စဉ်', ko: '일간' },
  Weekly: { en: 'Weekly', my: 'အပတ်စဉ်', ko: '주간' },
  Monthly: { en: 'Monthly', my: 'လစဉ်', ko: '월간' },
  Yearly: { en: 'Yearly', my: 'နှစ်စဉ်', ko: '연간' },
  Custom: { en: 'Custom', my: 'စိတ်ကြိုက်', ko: '사용자 지정' },
  From: { en: 'From', my: 'မှ', ko: '시작' },
  To: { en: 'To', my: 'အထိ', ko: '종료' },
  'Accounting & Reports': { en: 'Accounting & Reports', my: 'စာရင်းကိုင်နှင့် Report', ko: '회계 및 보고서' },
  'Server-aggregated totals with date-scoped accounting details.': { en: 'Server-aggregated totals with date-scoped accounting details.', my: 'ရက်စွဲအလိုက် server တွက်ချက်ထားသော စာရင်းချုပ်များ။', ko: '기간별 서버 집계 회계 상세입니다.' },
  PDF: { en: 'PDF', my: 'PDF', ko: 'PDF' },
  CSV: { en: 'CSV', my: 'CSV', ko: 'CSV' },
  Excel: { en: 'Excel', my: 'Excel', ko: 'Excel' },
  Print: { en: 'Print', my: 'Print ထုတ်ရန်', ko: '인쇄' },
  'Income received': { en: 'Income received', my: 'လက်ခံရရှိငွေ', ko: '수금액' },
  'Income Received': { en: 'Income Received', my: 'လက်ခံရရှိငွေ', ko: '수금액' },
  'Purchases & expenses': { en: 'Purchases & expenses', my: 'ဝယ်ယူမှုနှင့်အသုံးစရိတ်', ko: '구매 및 비용' },
  'Purchases & Expenses': { en: 'Purchases & Expenses', my: 'ဝယ်ယူမှုနှင့်အသုံးစရိတ်', ko: '구매 및 비용' },
  'Net Profit': { en: 'Net Profit', my: 'အသားတင်အမြတ်', ko: '순이익' },
  'completed orders': { en: 'completed orders', my: 'ပြီးဆုံး Order များ', ko: '완료 주문' },
  'Due collected': { en: 'Due collected', my: 'အကြွေးကောက်ခံပြီး', ko: '미수금 수금' },
  Returns: { en: 'Returns', my: 'ပြန်အမ်း/ပြန်ပို့', ko: '반품' },
  'Gross profit': { en: 'Gross profit', my: 'စုစုပေါင်းအမြတ်', ko: '매출총이익' },
  'Profit & Loss': { en: 'Profit & Loss', my: 'အမြတ် / အရှုံး', ko: '손익' },
  'Cost of goods': { en: 'Cost of goods', my: 'ကုန်ကျစရိတ်', ko: '매출원가' },
  'Operating expenses': { en: 'Operating expenses', my: 'လုပ်ငန်းအသုံးစရိတ်', ko: '운영 비용' },
  'Net profit': { en: 'Net profit', my: 'အသားတင်အမြတ်', ko: '순이익' },
  'Cash Flow': { en: 'Cash Flow', my: 'ငွေသားစီးဆင်းမှု', ko: '현금 흐름' },
  'Sales cash received': { en: 'Sales cash received', my: 'အရောင်းမှလက်ခံငွေ', ko: '판매 수금액' },
  'Due collection received': { en: 'Due collection received', my: 'အကြွေးကောက်ခံရရှိငွေ', ko: '미수금 수금액' },
  'Purchases paid': { en: 'Purchases paid', my: 'ဝယ်ယူမှု ပေးချေပြီး', ko: '구매 지급액' },
  'Purchase returns': { en: 'Purchase returns', my: 'ဝယ်ယူမှုပြန်ပို့', ko: '구매 반품' },
  'Expenses paid': { en: 'Expenses paid', my: 'အသုံးစရိတ်ပေးချေပြီး', ko: '비용 지급액' },
  'Owner withdrawals': { en: 'Owner withdrawals', my: 'ပိုင်ရှင်ထုတ်ငွေ', ko: '소유자 인출' },
  'Net cash flow': { en: 'Net cash flow', my: 'အသားတင်ငွေစီးဆင်းမှု', ko: '순현금흐름' },
  'Payment-method Totals': { en: 'Payment-method Totals', my: 'Payment Method အလိုက်စုစုပေါင်း', ko: '결제수단별 합계' },
  'Online versus In-store': { en: 'Online versus In-store', my: 'Online နှင့် ဆိုင်တွင်း', ko: '온라인 대비 매장' },
  'Category Performance': { en: 'Category Performance', my: 'Category Performance', ko: '카테고리 성과' },
  'Employee Sales': { en: 'Employee Sales', my: 'ဝန်ထမ်းအရောင်း', ko: '직원별 매출' },
  'Tax Summary & Credit Sales': { en: 'Tax Summary & Credit Sales', my: 'Tax Summary နှင့် အကြွေးအရောင်း', ko: '세금 요약 및 외상 매출' },
  'Tax collected': { en: 'Tax collected', my: 'ကောက်ခံ Tax', ko: '징수 세금' },
  'Outstanding credit': { en: 'Outstanding credit', my: 'ကျန်ရှိအကြွေး', ko: '미수 외상' },
  'Due collection': { en: 'Due collection', my: 'အကြွေးကောက်ခံမှု', ko: '미수금 수금' },
  'Product Profit': { en: 'Product Profit', my: 'Product အလိုက်အမြတ်', ko: '상품별 이익' },
  Product: { en: 'Product', my: 'Product', ko: '상품' },
  Qty: { en: 'Qty', my: 'အရေအတွက်', ko: '수량' },
  Cost: { en: 'Cost', my: 'ကုန်ကျစရိတ်', ko: '비용' },
  Profit: { en: 'Profit', my: 'အမြတ်', ko: '이익' },
  'Sales Detail': { en: 'Sales Detail', my: 'အရောင်းအသေးစိတ်', ko: '매출 상세' },
  Date: { en: 'Date', my: 'ရက်စွဲ', ko: '날짜' },
  Order: { en: 'Order', my: 'Order', ko: '주문' },
  Customer: { en: 'Customer', my: 'Customer', ko: '고객' },
  Employee: { en: 'Employee', my: 'ဝန်ထမ်း', ko: '직원' },
  Type: { en: 'Type', my: 'အမျိုးအစား', ko: '유형' },
  Total: { en: 'Total', my: 'စုစုပေါင်း', ko: '합계' },
  Due: { en: 'Due', my: 'ကျန်ငွေ', ko: '미수금' },
  'No records in this period.': { en: 'No records in this period.', my: 'ဤကာလအတွင်း မှတ်တမ်းမရှိပါ။', ko: '이 기간에는 기록이 없습니다.' },
  'No product sales in this period.': { en: 'No product sales in this period.', my: 'ဤကာလအတွင်း Product အရောင်းမရှိပါ။', ko: '이 기간에는 상품 매출이 없습니다.' },
  'No completed sales in this period.': { en: 'No completed sales in this period.', my: 'ဤကာလအတွင်း ပြီးဆုံးအရောင်းမရှိပါ။', ko: '이 기간에는 완료된 매출이 없습니다.' },
  'Due Collection': { en: 'Due Collection', my: 'အကြွေးကောက်ခံခြင်း', ko: '미수금 수금' },
  'Record a customer credit payment and atomically update the order balance.': { en: 'Record a customer credit payment and atomically update the order balance.', my: 'Customer အကြွေးပေးချေမှုကို မှတ်ပြီး order balance ကိုတပြိုင်နက် update လုပ်ပါ။', ko: '고객 외상 결제를 기록하고 주문 잔액을 함께 업데이트합니다.' },
  'Select outstanding order': { en: 'Select outstanding order', my: 'ကျန်ငွေရှိသော Order ရွေးရန်', ko: '미수 주문 선택' },
  'Reference (optional)': { en: 'Reference (optional)', my: 'Reference (မဖြစ်မနေမဟုတ်)', ko: '참조번호 (선택)' },
  'Collect Payment': { en: 'Collect Payment', my: 'ငွေကောက်ခံရန်', ko: '결제 수금' },
  'Due payment recorded.': { en: 'Due payment recorded.', my: 'အကြွေးပေးချေမှု မှတ်ပြီးပါပြီ။', ko: '미수금 결제가 기록되었습니다.' },
  'App Download': { en: 'App Download', my: 'App ဒေါင်းလုဒ်', ko: '앱 다운로드' },
  'Download app': { en: 'Download app', my: 'App ဒေါင်းလုဒ်လုပ်ရန်', ko: '앱 다운로드' },
  'No App Store Required': { en: 'No App Store Required', my: 'App Store မလိုပါ', ko: '앱 스토어 불필요' },
  'Download or install KI3 POS from this link': { en: 'Download or install KI3 POS from this link', my: 'ဒီ link ကနေ KI3 POS ကို install/download လုပ်ပါ', ko: '이 링크에서 KI3 POS를 다운로드하거나 설치하세요' },
  'Use this public page for owners and employees who need the POS app without publishing it on Play Store or App Store.': { en: 'Use this public page for owners and employees who need the POS app without publishing it on Play Store or App Store.', my: 'Play Store / App Store မတင်ဘဲ ဆိုင်ရှင်နှင့်ဝန်ထမ်းများ POS app သုံးနိုင်ရန် ဒီ public page ကိုသုံးပါ။', ko: 'Play Store 또는 App Store에 게시하지 않고 소유자와 직원이 POS 앱을 사용할 수 있도록 이 공개 페이지를 사용하세요.' },
  Installed: { en: 'Installed', my: 'Install လုပ်ပြီး', ko: '설치됨' },
  'Install KI3 POS': { en: 'Install KI3 POS', my: 'KI3 POS Install လုပ်ရန်', ko: 'KI3 POS 설치' },
  'Open in Chrome to Install': { en: 'Open in Chrome to Install', my: 'Install လုပ်ရန် Chrome ဖြင့်ဖွင့်ပါ', ko: '설치하려면 Chrome에서 여세요' },
  'Open Web App': { en: 'Open Web App', my: 'Web App ဖွင့်ရန်', ko: '웹 앱 열기' },
  'Android APK direct download can be enabled after a real APK is built and uploaded. This computer currently needs Java JDK and Android SDK/Android Studio before APK build.': { en: 'Android APK direct download can be enabled after a real APK is built and uploaded. This computer currently needs Java JDK and Android SDK/Android Studio before APK build.', my: 'Android APK direct download ကို APK အမှန် build/upload လုပ်ပြီးမှ ဖွင့်နိုင်ပါမယ်။ ဒီကွန်ပျူတာမှာ APK build မလုပ်ခင် Java JDK နှင့် Android SDK/Android Studio လိုနေပါသည်။', ko: '실제 APK를 빌드하고 업로드한 후 Android APK 직접 다운로드를 활성화할 수 있습니다. 이 컴퓨터는 APK 빌드 전에 Java JDK와 Android SDK/Android Studio가 필요합니다.' },
  Android: { en: 'Android', my: 'Android', ko: 'Android' },
  'Open this page in Chrome and press Install KI3 POS. When APK is ready, an APK download button can be added here.': { en: 'Open this page in Chrome and press Install KI3 POS. When APK is ready, an APK download button can be added here.', my: 'ဒီ page ကို Chrome ဖြင့်ဖွင့်ပြီး Install KI3 POS ကိုနှိပ်ပါ။ APK အဆင်သင့်ဖြစ်လျှင် APK download button ကို ဒီနေရာမှာထည့်နိုင်ပါသည်။', ko: 'Chrome에서 이 페이지를 열고 KI3 POS 설치를 누르세요. APK가 준비되면 여기에 APK 다운로드 버튼을 추가할 수 있습니다.' },
  'iPhone / iPad': { en: 'iPhone / iPad', my: 'iPhone / iPad', ko: 'iPhone / iPad' },
  'Open with Safari, tap Share, then choose Add to Home Screen. Apple does not allow simple public IPA download installs like Android APK.': { en: 'Open with Safari, tap Share, then choose Add to Home Screen. Apple does not allow simple public IPA download installs like Android APK.', my: 'Safari ဖြင့်ဖွင့်ပြီး Share ကိုနှိပ်ပါ၊ ထို့နောက် Add to Home Screen ရွေးပါ။ Apple မှာ Android APK လို public IPA direct install မရပါ။', ko: 'Safari에서 열고 공유를 누른 다음 홈 화면에 추가를 선택하세요. Apple은 Android APK처럼 공개 IPA 직접 설치를 허용하지 않습니다.' },
  Desktop: { en: 'Desktop', my: 'Desktop', ko: '데스크톱' },
  'Chrome and Edge can install KI3 POS as a desktop app from the browser install icon.': { en: 'Chrome and Edge can install KI3 POS as a desktop app from the browser install icon.', my: 'Chrome နှင့် Edge တွင် browser install icon ကနေ KI3 POS ကို desktop app အဖြစ် install လုပ်နိုင်ပါသည်။', ko: 'Chrome과 Edge에서는 브라우저 설치 아이콘으로 KI3 POS를 데스크톱 앱처럼 설치할 수 있습니다.' },
};

export function translate(label: string, language: AppLanguage) {
  if (language === 'en') return label;
  const exact = dictionary[label]?.[language];
  if (exact) return exact;
  if (label.endsWith(' Dashboard')) return label.replace(' Dashboard', ` ${translate('Dashboard', language)}`);
  return label;
}
