import { useState } from 'react';
import { Bell, Database, Gift, RotateCcw, Tags, Users } from 'lucide-react';
import DashboardLayout from '@/layouts/DashboardLayout';
import { Button, Card, DataState, Input } from '@/components/ui';
import { downloadText } from '@/lib/actions';
import { createShopBackup, parseShopBackup, restoreShopBackup } from '@/lib/backup';
import { useAuth } from '@/lib/auth';
import { createRecord, refundOrder, returnPurchase, setRecord, updateRecord, useLiveCollection } from '@/lib/firestore';
import { formatCurrency } from '@/lib/utils';
import type { AuditLog, Coupon, Customer, ExpenseCategory, Order, Promotion, Purchase, PurchaseReturn, SalesReturn, ShopNotification } from '@/types';
import { useConfirm, useToast } from '@/lib/feedback';

type Tab = 'RETURNS' | 'CUSTOMERS' | 'CAMPAIGNS' | 'NOTIFICATIONS' | 'DATA';
const today = () => new Date().toISOString().slice(0, 10);
const inThirtyDays = () => { const date = new Date(); date.setDate(date.getDate() + 30); return date.toISOString().slice(0, 10); };

export default function OwnerCoreModules() {
  const { user } = useAuth(); const shopId = user?.shopId || '';
  const confirm = useConfirm(); const toast = useToast();
  const path = (name: string) => shopId ? `shops/${shopId}/${name}` : null;
  const { data: purchases } = useLiveCollection<Purchase>(path('purchases'), 'createdAt');
  const { data: purchaseReturns } = useLiveCollection<PurchaseReturn>(path('purchaseReturns'), 'createdAt');
  const { data: orders } = useLiveCollection<Order>(path('orders'), 'createdAt');
  const { data: salesReturns } = useLiveCollection<SalesReturn>(path('salesReturns'), 'createdAt');
  const { data: customers } = useLiveCollection<Customer>(path('customers'), 'updatedAt');
  const { data: categories } = useLiveCollection<ExpenseCategory>(path('expenseCategories'), 'createdAt');
  const { data: promotions } = useLiveCollection<Promotion>(path('promotions'), 'createdAt');
  const { data: coupons } = useLiveCollection<Coupon>(path('coupons'), 'createdAt');
  const { data: notifications } = useLiveCollection<ShopNotification>(path('notifications'), 'createdAt');
  const { data: audits } = useLiveCollection<AuditLog>(path('auditLogs'), 'createdAt');
  const [tab, setTab] = useState<Tab>('RETURNS'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [purchaseReturn, setPurchaseReturn] = useState({ purchaseId: '', quantity: '1', reason: '' });
  const [saleReturn, setSaleReturn] = useState({ orderId: '', reason: '' });
  const [customer, setCustomer] = useState({ name: '', phone: '' }); const [points, setPoints] = useState<Record<string, string>>({});
  const [category, setCategory] = useState('');
  const [promotion, setPromotion] = useState({ name: '', type: 'PERCENT' as 'PERCENT'|'FIXED', value: '', minimumPurchase: '0', startsAt: today(), endsAt: inThirtyDays() });
  const [coupon, setCoupon] = useState({ code: '', name: '', type: 'PERCENT' as 'PERCENT'|'FIXED', value: '', minimumPurchase: '0', usageLimit: '100', startsAt: today(), endsAt: inThirtyDays() });
  const [notification, setNotification] = useState({ title: '', message: '', audience: 'ALL' as 'ALL'|'OWNER'|'EMPLOYEE' });
  const audit = (action:string,detail:string) => createRecord(`shops/${shopId}/auditLogs`,{shopId,actorId:user!.id,actorName:user!.name,action,detail,createdAt:new Date().toISOString()});
  const run = async (action:()=>Promise<unknown>, success:string) => { setBusy(true); setMessage(''); try { await action(); setMessage(success); toast(success); } catch (issue) { const text=issue instanceof Error?issue.message:'Unable to complete this action.';setMessage(text);toast(text,'error'); } finally { setBusy(false); } };

  const savePurchaseReturn = () => run(async()=>{const purchase=purchases.find(item=>item.id===purchaseReturn.purchaseId);if(!purchase)throw new Error('Select a purchase.');await returnPurchase(shopId,purchase.id,{quantity:Number(purchaseReturn.quantity),reason:purchaseReturn.reason.trim()||'Returned to supplier',actorId:user!.id,actorName:user!.name});await audit('PURCHASE_RETURNED',`${purchase.productName} × ${purchaseReturn.quantity}`);setPurchaseReturn({purchaseId:'',quantity:'1',reason:''})},'Purchase return recorded and stock updated.');
  const saveSalesReturn = () => run(async()=>{const order=orders.find(item=>item.id===saleReturn.orderId);if(!order)throw new Error('Select a completed sale.');await refundOrder(shopId,order,saleReturn.reason.trim()||'Customer return');await audit('SALES_RETURNED',order.orderNumber||order.id);setSaleReturn({orderId:'',reason:''})},'Sales return recorded and stock restored.');
  const saveCustomer = () => run(async()=>{if(!customer.name.trim()||!customer.phone.trim())throw new Error('Enter customer name and phone.');const id=customer.phone.replace(/\W/g,'');await setRecord(`shops/${shopId}/customers`,id,{name:customer.name.trim(),phone:customer.phone.trim(),totalSpent:0,visits:0,loyaltyPoints:0,outstandingCredit:0,updatedAt:new Date().toISOString()});await audit('CUSTOMER_CREATED',customer.name);setCustomer({name:'',phone:''})},'Customer saved.');
  const adjustPoints = (item:Customer) => run(async()=>{const adjustment=Number(points[item.id]);if(!Number.isFinite(adjustment)||adjustment===0)throw new Error('Enter a non-zero points adjustment.');const next=Math.max(0,(item.loyaltyPoints||0)+adjustment);await updateRecord(`shops/${shopId}/customers`,item.id,{loyaltyPoints:next,updatedAt:new Date().toISOString()});await audit('LOYALTY_POINTS_ADJUSTED',`${item.name}: ${adjustment>0?'+':''}${adjustment}`);setPoints(current=>({...current,[item.id]:''}))},'Loyalty points updated.');
  const addCategory = () => run(async()=>{if(!category.trim())throw new Error('Enter a category name.');await createRecord(`shops/${shopId}/expenseCategories`,{shopId,name:category.trim(),active:true,createdAt:new Date().toISOString()});await audit('EXPENSE_CATEGORY_CREATED',category);setCategory('')},'Expense category saved.');
  const addPromotion = () => run(async()=>{if(!promotion.name.trim()||Number(promotion.value)<=0)throw new Error('Enter a promotion and value.');await createRecord(`shops/${shopId}/promotions`,{...promotion,value:Number(promotion.value),minimumPurchase:Number(promotion.minimumPurchase)||0,shopId,active:true,createdAt:new Date().toISOString()});await audit('PROMOTION_CREATED',promotion.name);setPromotion({...promotion,name:'',value:''})},'Promotion saved.');
  const addCoupon = () => run(async()=>{if(!coupon.code.trim()||!coupon.name.trim()||Number(coupon.value)<=0)throw new Error('Enter coupon code, name and value.');await createRecord(`shops/${shopId}/coupons`,{...coupon,code:coupon.code.trim().toUpperCase(),value:Number(coupon.value),minimumPurchase:Number(coupon.minimumPurchase)||0,usageLimit:Number(coupon.usageLimit)||0,usedCount:0,shopId,active:true,createdAt:new Date().toISOString()});await audit('COUPON_CREATED',coupon.code.toUpperCase());setCoupon({...coupon,code:'',name:'',value:''})},'Coupon saved.');
  const addNotification = () => run(async()=>{if(!notification.title.trim()||!notification.message.trim())throw new Error('Enter title and message.');await createRecord(`shops/${shopId}/notifications`,{...notification,shopId,active:true,createdBy:user!.id,createdAt:new Date().toISOString()});await audit('NOTIFICATION_CREATED',notification.title);setNotification({title:'',message:'',audience:'ALL'})},'Notification published.');
  const exportBackup = () => run(async()=>{const backup=await createShopBackup(shopId);downloadText(`ki3-backup-${shopId}-${today()}.json`,JSON.stringify(backup,null,2),'application/json') ;await audit('BACKUP_EXPORTED',backup.createdAt)},'Backup downloaded.');
  const importBackup = (file?:File) => { if(!file)return; void run(async()=>{if(!await confirm({title:'Restore shop backup?',message:'Existing matching records in this shop will be merged with the selected backup. Authentication accounts and immutable logs are not changed.',confirmLabel:'Restore Backup',danger:true}))return;const backup=parseShopBackup(await file.text(),shopId);const count=await restoreShopBackup(backup);await audit('BACKUP_RESTORED',`${count} records from ${backup.createdAt}`)},'Backup restored. Reload to see all restored records.'); };
  const availablePurchases=purchases.filter(item=>(item.returnedQuantity||0)<item.quantity); const refundableOrders=orders.filter(item=>item.status==='COMPLETED');

  return <DashboardLayout role="OWNER"><div className="space-y-6"><div><h1 className="text-3xl font-black">Core Modules</h1><p className="mt-2 text-slate-500">Returns, customer loyalty, campaigns, notifications and data safety.</p></div>
    <div className="flex gap-2 overflow-x-auto">{([['RETURNS',RotateCcw,'Returns'],['CUSTOMERS',Users,'Customers & Categories'],['CAMPAIGNS',Gift,'Promotions & Coupons'],['NOTIFICATIONS',Bell,'Notifications'],['DATA',Database,'Backup & Logs']] as const).map(([value,Icon,label])=><button key={value} onClick={()=>setTab(value)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab===value?'bg-blue-600 text-white':'border bg-white text-slate-600'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div>
    {message&&<p role="status" className="rounded-2xl bg-blue-50 p-4 text-sm font-bold text-blue-700">{message}</p>}
    {tab==='RETURNS'&&<div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><Card className="space-y-3"><h2 className="font-black">Purchase Return</h2><Select value={purchaseReturn.purchaseId} onChange={purchaseId=>setPurchaseReturn({...purchaseReturn,purchaseId})} options={[['','Select purchase'],...availablePurchases.map(item=>[item.id,`${item.productName} · available ${item.quantity-(item.returnedQuantity||0)}`]) ]}/><Input type="number" min="1" value={purchaseReturn.quantity} onChange={event=>setPurchaseReturn({...purchaseReturn,quantity:event.target.value})}/><Input placeholder="Return reason" value={purchaseReturn.reason} onChange={event=>setPurchaseReturn({...purchaseReturn,reason:event.target.value})}/><Button disabled={busy||!purchaseReturn.purchaseId} onClick={savePurchaseReturn}>Return to Supplier</Button></Card><Card className="space-y-3"><h2 className="font-black">Sales Return / Refund</h2><Select value={saleReturn.orderId} onChange={orderId=>setSaleReturn({...saleReturn,orderId})} options={[['','Select completed order'],...refundableOrders.map(item=>[item.id,`${item.orderNumber||item.id} · ${formatCurrency(item.total)}`])]}/><Input placeholder="Return reason" value={saleReturn.reason} onChange={event=>setSaleReturn({...saleReturn,reason:event.target.value})}/><Button variant="danger" disabled={busy||!saleReturn.orderId} onClick={saveSalesReturn}>Refund & Restock Sale</Button></Card></div><div className="grid gap-6 xl:grid-cols-2"><Table title="Purchase Returns" headers={['Date','Product','Qty','Total','Reason']} rows={purchaseReturns.map(item=>[new Date(item.createdAt).toLocaleString(),item.productName,item.quantity,formatCurrency(item.total),item.reason])}/><Table title="Sales Returns" headers={['Date','Order','Customer','Total','Reason']} rows={salesReturns.map(item=>[new Date(item.createdAt).toLocaleString(),item.orderNumber,item.customer,formatCurrency(item.total),item.reason])}/></div></div>}
    {tab==='CUSTOMERS'&&<div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><Card className="space-y-3"><h2 className="font-black">Add Customer</h2><Input placeholder="Customer name" value={customer.name} onChange={event=>setCustomer({...customer,name:event.target.value})}/><Input placeholder="Phone" value={customer.phone} onChange={event=>setCustomer({...customer,phone:event.target.value})}/><Button disabled={busy} onClick={saveCustomer}>Save Customer</Button></Card><Card className="space-y-3"><h2 className="font-black">Expense Categories</h2><div className="flex gap-2"><Input placeholder="Category name" value={category} onChange={event=>setCategory(event.target.value)}/><Button disabled={busy} onClick={addCategory}><Tags className="mr-2 h-4 w-4"/>Add</Button></div><div className="flex flex-wrap gap-2">{categories.map(item=><span key={item.id} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold">{item.name}</span>)}</div></Card></div><Card><h2 className="mb-4 font-black">Customer Loyalty & Credit</h2><div className="space-y-3">{customers.map(item=><div key={item.id} className="grid items-center gap-3 rounded-2xl border p-3 md:grid-cols-[1fr_auto_auto_auto]"><div><p className="font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.phone} · {item.visits||0} visits · Credit {formatCurrency(item.outstandingCredit||0)}</p></div><p className="text-sm font-black">{item.loyaltyPoints||0} pts</p><Input className="md:w-28" type="number" placeholder="± points" value={points[item.id]||''} onChange={event=>setPoints({...points,[item.id]:event.target.value})}/><Button variant="outline" onClick={()=>adjustPoints(item)}>Adjust</Button></div>)}<DataState empty={!customers.length} emptyMessage="No customers yet."/></div></Card></div>}
    {tab==='CAMPAIGNS'&&<div className="grid gap-6 xl:grid-cols-2"><CampaignCard title="Create Promotion" data={promotion} setData={setPromotion} save={addPromotion}/><CouponCard data={coupon} setData={setCoupon} save={addCoupon}/><Table title="Promotions" headers={['Name','Discount','Minimum','Period','Status']} rows={promotions.map(item=>[item.name,`${item.value}${item.type==='PERCENT'?'%':' MMK'}`,formatCurrency(item.minimumPurchase),`${item.startsAt} → ${item.endsAt}`,item.active?'Active':'Inactive'])}/><Table title="Coupons" headers={['Code','Name','Discount','Usage','Status']} rows={coupons.map(item=>[item.code,item.name,`${item.value}${item.type==='PERCENT'?'%':' MMK'}`,`${item.usedCount}/${item.usageLimit}`,item.active?'Active':'Inactive'])}/></div>}
    {tab==='NOTIFICATIONS'&&<div className="grid gap-6 lg:grid-cols-3"><Card className="space-y-3"><h2 className="font-black">Publish Notification</h2><Input placeholder="Title" value={notification.title} onChange={event=>setNotification({...notification,title:event.target.value})}/><textarea className="control h-28 w-full py-3" placeholder="Message" value={notification.message} onChange={event=>setNotification({...notification,message:event.target.value})}/><Select value={notification.audience} onChange={audience=>setNotification({...notification,audience:audience as typeof notification.audience})} options={[['ALL','All shop users'],['OWNER','Owners'],['EMPLOYEE','Employees']]}/><Button disabled={busy} onClick={addNotification}>Publish</Button></Card><div className="space-y-3 lg:col-span-2">{notifications.map(item=><Card key={item.id}><div className="flex justify-between"><div><p className="font-black">{item.title}</p><p className="mt-2 text-sm text-slate-600">{item.message}</p></div><span className="text-xs font-bold text-blue-600">{item.audience}</span></div><p className="mt-3 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></Card>)}<DataState empty={!notifications.length} emptyMessage="No shop notifications."/></div></div>}
    {tab==='DATA'&&<div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="font-black">Backup</h2><p className="my-3 text-sm text-slate-500">Download operational shop data as a versioned JSON file. Authentication accounts are intentionally excluded.</p><Button disabled={busy} onClick={exportBackup}>Download Backup</Button></Card><Card><h2 className="font-black">Restore</h2><p className="my-3 text-sm text-slate-500">Only a backup created for this exact Shop ID can be restored. Existing matching records are merged.</p><label className="inline-flex cursor-pointer rounded-2xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Choose Backup<input type="file" accept="application/json" className="hidden" onChange={event=>{importBackup(event.target.files?.[0]);event.currentTarget.value=''}}/></label></Card></div><Table title="Activity Logs" headers={['Date','User','Action','Detail']} rows={audits.slice(0,100).map(item=>[new Date(item.createdAt).toLocaleString(),item.actorName,item.action,item.detail])}/><Table title="Immutable Audit Logs" headers={['ID','Date','Actor ID','Action']} rows={audits.slice(0,100).map(item=>[item.id,new Date(item.createdAt).toLocaleString(),item.actorId,item.action])}/></div>}
  </div></DashboardLayout>;
}

function Select({value,onChange,options}:{value:string;onChange(value:string):void;options:string[][]}){return <select className="control w-full" value={value} onChange={event=>onChange(event.target.value)}>{options.map(([key,label])=><option key={`${key}-${label}`} value={key}>{label}</option>)}</select>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:Array<Array<string|number>>}){return <Card className="overflow-hidden p-0"><h2 className="p-5 font-black">{title}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{headers.map(item=><th key={item} className="px-4 py-3 text-xs uppercase text-slate-500">{item}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex} className="whitespace-nowrap px-4 py-3">{cell}</td>)}</tr>)}</tbody></table><DataState empty={!rows.length} emptyMessage="No records yet."/></div></Card>}
function CampaignFields({data,setData}:{data:{type:'PERCENT'|'FIXED';value:string;minimumPurchase:string;startsAt:string;endsAt:string};setData(value:any):void}){return <><div className="grid grid-cols-2 gap-3"><Select value={data.type} onChange={type=>setData({...data,type})} options={[['PERCENT','Percentage'],['FIXED','Fixed amount']]}/><Input type="number" min="0" placeholder="Discount value" value={data.value} onChange={event=>setData({...data,value:event.target.value})}/></div><Input type="number" min="0" placeholder="Minimum purchase" value={data.minimumPurchase} onChange={event=>setData({...data,minimumPurchase:event.target.value})}/><div className="grid grid-cols-2 gap-3"><Input type="date" value={data.startsAt} onChange={event=>setData({...data,startsAt:event.target.value})}/><Input type="date" value={data.endsAt} onChange={event=>setData({...data,endsAt:event.target.value})}/></div></>}
function CampaignCard({title,data,setData,save}:{title:string;data:any;setData(value:any):void;save():void}){return <Card className="space-y-3"><h2 className="font-black">{title}</h2><Input placeholder="Promotion name" value={data.name} onChange={event=>setData({...data,name:event.target.value})}/><CampaignFields data={data} setData={setData}/><Button onClick={save}>Save Promotion</Button></Card>}
function CouponCard({data,setData,save}:{data:any;setData(value:any):void;save():void}){return <Card className="space-y-3"><h2 className="font-black">Create Coupon</h2><div className="grid grid-cols-2 gap-3"><Input placeholder="Code" value={data.code} onChange={event=>setData({...data,code:event.target.value.toUpperCase()})}/><Input placeholder="Coupon name" value={data.name} onChange={event=>setData({...data,name:event.target.value})}/></div><CampaignFields data={data} setData={setData}/><Input type="number" min="0" placeholder="Usage limit" value={data.usageLimit} onChange={event=>setData({...data,usageLimit:event.target.value})}/><Button onClick={save}>Save Coupon</Button></Card>}
